ALTER TABLE bags DROP CONSTRAINT FK_bags_person
ALTER TABLE deposits DROP CONSTRAINT FK_deposits_depositList
DROP TABLE bags CASCADE
DROP TABLE countries CASCADE
DROP TABLE deposits CASCADE
DROP TABLE persons CASCADE
